[package]
name = "wasm_safe_mutex"
version = "0.1.2"
edition = "2024"
authors = ["Drew Crawford <drew@sealedabstract.com>"]
repository = "https://github.com/drewcrawford/wasm_safe_mutex"
homepage = "https://sealedabstract.com/code/wasm_safe_mutex"
description = "A suite of WebAssembly-safe synchronization primitives that paper over platform-specific locking constraints."
license = "MIT OR Apache-2.0"
keywords = ["concurrency", "lock", "mutex", "spinlock", "wasm"]
categories = ["concurrency", "wasm", "asynchronous", "rust-patterns", "web-programming"]
exclude = [".*"]
rust-version = "1.85.1"

[dependencies]
continue = "0.1.1"

[dev-dependencies]
test_executors = "0.4.1"

[target.'cfg(target_arch="wasm32")'.dependencies]
web-time = "1.1"
wasm-bindgen = "0.2.106"
wasm_thread = "0.3.3"

[target.'cfg(target_arch="wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

