[package]
name = "wasm_safe_mutex"
version = "0.1.0"
edition = "2024"
authors = ["Drew Crawford <drew@sealedabstract.com>"]
repository = "https://github.com/drewcrawford/wasm_safe_mutex"
homepage = "https://sealedabstract.com/code/wasm_safe_mutex"
description = "A mutex safe for use in browsers on the main thread"
license = "MIT OR Apache-2.0"
keywords = ["concurrency", "lock", "mutex", "spinlock", "wasm"]
categories = ["asynchronous", "concurrency", "wasm" ]
exclude = [".*"]
rust-version = "1.85.0" # todo?

[dependencies]
continue = "0.1"

[dev-dependencies]
test_executors = "0.3.5"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2"

[target.'cfg(target_arch="wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
wasm_thread = "0.3"

[patch.crates-io]

